# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
# Stacks detected: cicd:gitlab-workflows:.
version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
    working_directory: ~/aura-pi-gen
    resource_class: medium

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: ./test.sh

  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Working Directory
          command: pwd
      - run:
          name: List Directory
          command: ls -la
      - run:
          name: Build with Docker
          command: ./build-docker.sh
      - store_artifacts:
          path: deploy

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
      - run:
          name: Create GitHub Release
          command: |
            gh auth login --with-token < $GITHUB_TOKEN
            gh release create v1.0.0 ./deploy/* --title "Release v1.0.0" --notes "Automated release from CircleCI"

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build