version: 2.1
executors:
  docker-executor:
    docker:
      - image: docker:20.10.7
    working_directory: ~/aura-pi-gen
    resource_class: medium

jobs:
  test:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - run:
          name: Run tests
          command: ./test.sh

  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build with Docker
          command: |
            echo "Current directory: $(pwd)"
            echo "Listing files:"
            ls -la
            if [ ! -f ./build-docker.sh ]; then
              echo "ERROR: build-docker.sh not found in $(pwd)"
              exit 1
            fi
            chmod +x ./build-docker.sh
            ./build-docker.sh
      - store_artifacts:
          path: deploy

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Install GitHub CLI
          command: |
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh
      - run:
          name: Create GitHub Release
          command: |
            gh auth login --with-token < $GITHUB_TOKEN
            gh release create v1.0.0 ./deploy/* --title "Release v1.0.0" --notes "Automated release from CircleCI"

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
